name: Build && Deploy to Firebase
on: workflow_dispatch

jobs:
  deploy-to-firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieving Main Repo
        uses: actions/checkout@v3
      - name: Setting up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Installing node modules && Building
        run: |
          npm ci
          npm run build
      - name: Setting up firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}